Universe	= vanilla
Executable 	= JetVal_Script.sh
notification 	= Never
Output  	= /sphenix/u/jlnliu/sphnx_software/analysis/JS-Jet/JetValidation/macro/condor/logs/condor$(process).out
Error           = /sphenix/u/jlnliu/sphnx_software/analysis/JS-Jet/JetValidation/macro/condor/logs/condor$(process).err
Log  		= /tmp/condor_jlnliu_$(process).log
Arguments 	= "$(Process)"	
Initialdir  	= /sphenix/u/jlnliu/sphnx_software/analysis/JS-Jet/JetValidation/macro/
request_memory = 4096MB
PeriodicHold = (NumJobStarts>=1 && JobStatus == 1)
Queue 100
